name: TEST

on:
  workflow_dispatch:
  
jobs:
  issue:
    name: Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 
      - name: pip
        run: pip install jira GitPython
      - name: pip freeze
        run: pip freeze
      - name: modules
        run: python -c "help('modules')"
